min_version = "2026.7.5"

[settings]
lockfile = true

[tools]
biome = "2.5.8"
node = "24.19.0"
"aqua:jdx/aube" = "1.39.0"

[task_config]
includes = [
  "git::https://github.com/iwamot/mise-tasks.git//.mise/tasks?ref=v2.5.1",
]
