/**
 * Check the vendored wire schemas and compile them into a module.
 *
 * `schema/*.json` arrives from Welt through Oide, so it is a copy rather
 * than the original: a truncated pull or a partial write would leave the
 * adapter checking payloads against something that is not a schema at all.
 * This reads each one, refuses it unless it parses and is a valid 2020-12
 * schema, and writes what it read into the package as `src/_schema.ts`.
 *
 * Compiling them in rather than reading them at run time keeps the schemas
 * where the package is, whatever the repository does with `schema/` —
 * nothing to add to the published files, and no file that can go missing
 * once installed.
 *
 * `validate.sh` runs this, so a schema that has moved on without the module
 * fails on the diff.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { AnySchema } from "ajv/dist/2020.js";
import { Ajv2020 } from "ajv/dist/2020.js";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUTPUT = join(ROOT, "src", "_schema.ts");
const SCHEMAS = [
  ["REQUEST_PAYLOAD", "request-payload"],
  ["REPLY_EVENTS", "reply-events"],
] as const;
const HEADER =
  "/** The wire schemas, generated by scripts/generate-schema.ts. */";

// strict: false — the schemas are Welt's, written to the specification
// rather than to Ajv's stricter reading of it.
const ajv = new Ajv2020({ strict: false });

/**
 * Read one vendored schema, refusing what is not one.
 *
 * @param name - The schema's file name, without the suffix.
 * @returns The schema.
 * @throws {SyntaxError} If the file is not JSON.
 * @throws {Error} If it is JSON but not a valid 2020-12 schema.
 */
function checkedSchema(name: string): AnySchema {
  const source = readFileSync(
    join(ROOT, "schema", `${name}.schema.json`),
    "utf8",
  );
  // Whether the file really holds a schema is what the check below says;
  // the cast only gets it that far.
  const schema = JSON.parse(source) as AnySchema;
  ajv.validateSchema(schema, true);
  return schema;
}

const parts = [HEADER];
for (const [constant, name] of SCHEMAS) {
  parts.push(
    `export const ${constant} = ${JSON.stringify(checkedSchema(name), null, 2)};`,
  );
}
writeFileSync(OUTPUT, `${parts.join("\n\n")}\n`);
