/** The wire schemas, generated by scripts/generate-schema.ts. */

export const REQUEST_PAYLOAD = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  title: "Welt request payload",
  description:
    "The JSON Welt sends to the agent, specified in prose by docs/wire.md. A payload that fails this schema is a bug on the sending side; see the wire contract's Malformed payloads section for what an adapter may do about it. What this schema cannot express stays in the prose: the content block order, the speaker prefix of a user text, and the suffix that keeps document names unique.",
  oneOf: [
    {
      type: "object",
      required: ["messages"],
      additionalProperties: false,
      properties: {
        messages: {
          $ref: "#/$defs/messages",
        },
      },
    },
    {
      type: "object",
      required: ["interrupt_responses"],
      additionalProperties: false,
      properties: {
        interrupt_responses: {
          $ref: "#/$defs/interruptResponses",
        },
      },
    },
  ],
  $defs: {
    messages: {
      title: "A conversation turn",
      description:
        "The Slack thread as Bedrock Converse-shaped messages, oldest first. Never empty, and the first message is always a user one.",
      type: "array",
      minItems: 1,
      prefixItems: [
        {
          $ref: "#/$defs/userMessage",
        },
      ],
      items: {
        $ref: "#/$defs/message",
      },
    },
    message: {
      oneOf: [
        {
          $ref: "#/$defs/userMessage",
        },
        {
          $ref: "#/$defs/assistantMessage",
        },
      ],
    },
    userMessage: {
      description: "A Slack message, which carries the uploads it came with.",
      type: "object",
      required: ["role", "content"],
      additionalProperties: false,
      properties: {
        role: {
          const: "user",
        },
        content: {
          type: "array",
          minItems: 1,
          items: {
            oneOf: [
              {
                $ref: "#/$defs/textBlock",
              },
              {
                $ref: "#/$defs/imageBlock",
              },
              {
                $ref: "#/$defs/documentBlock",
              },
              {
                $ref: "#/$defs/videoBlock",
              },
            ],
          },
        },
      },
    },
    assistantMessage: {
      description:
        "One of Welt's own earlier replies, which is text and nothing else.",
      type: "object",
      required: ["role", "content"],
      additionalProperties: false,
      properties: {
        role: {
          const: "assistant",
        },
        content: {
          type: "array",
          minItems: 1,
          items: {
            $ref: "#/$defs/textBlock",
          },
        },
      },
    },
    textBlock: {
      type: "object",
      required: ["text"],
      additionalProperties: false,
      properties: {
        text: {
          type: "string",
          minLength: 1,
        },
      },
    },
    imageBlock: {
      type: "object",
      required: ["image"],
      additionalProperties: false,
      properties: {
        image: {
          type: "object",
          required: ["format", "source"],
          additionalProperties: false,
          properties: {
            format: {
              enum: ["gif", "jpeg", "png", "webp"],
            },
            source: {
              $ref: "#/$defs/source",
            },
          },
        },
      },
    },
    documentBlock: {
      type: "object",
      required: ["document"],
      additionalProperties: false,
      properties: {
        document: {
          type: "object",
          required: ["format", "name", "source"],
          additionalProperties: false,
          properties: {
            format: {
              enum: [
                "csv",
                "doc",
                "docx",
                "html",
                "md",
                "pdf",
                "txt",
                "xls",
                "xlsx",
              ],
            },
            name: {
              description:
                "The document's handle for the model, not the Slack file name: what Converse accepts of it, made unique within the payload. The length and the characters are Converse's own conditions — a name outside them is a request Bedrock refuses.",
              type: "string",
              minLength: 1,
              maxLength: 200,
              pattern: "^[0-9A-Za-z()\\[\\] -]+$",
            },
            source: {
              $ref: "#/$defs/source",
            },
          },
        },
      },
    },
    videoBlock: {
      type: "object",
      required: ["video"],
      additionalProperties: false,
      properties: {
        video: {
          type: "object",
          required: ["format", "source"],
          additionalProperties: false,
          properties: {
            format: {
              enum: [
                "flv",
                "mkv",
                "mov",
                "mp4",
                "mpeg",
                "mpg",
                "three_gp",
                "webm",
                "wmv",
              ],
            },
            source: {
              $ref: "#/$defs/source",
            },
          },
        },
      },
    },
    source: {
      type: "object",
      required: ["bytes"],
      additionalProperties: false,
      properties: {
        bytes: {
          description:
            "The file's bytes, base64-encoded because JSON carries no raw bytes. Whether the string decodes is left to whatever decodes it: contentEncoding annotates, it does not assert.",
          type: "string",
          minLength: 1,
          contentEncoding: "base64",
        },
      },
    },
    interruptResponses: {
      title: "Answers resuming an interrupted run",
      description:
        "The answer a human gave per interrupt id — a button's value, or the submitted text. Welt sends it only once every pending question is answered, so it is never empty.",
      type: "object",
      minProperties: 1,
      additionalProperties: {
        type: "string",
      },
    },
  },
};

export const REPLY_EVENTS = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  title: "Welt reply event",
  description:
    "One event of the agent's reply stream, specified in prose by docs/wire.md. Unlike the request payload, this direction is not a rejection contract: Welt reads the six keys named here and ignores everything else. So this states one thing only — if an event carries one of the six, this is the shape Welt reads it in. Everything else about the event is the framework's own business.",
  type: "object",
  properties: {
    data: {
      $ref: "#/$defs/data",
    },
    current_tool_use: {
      $ref: "#/$defs/currentToolUse",
    },
    tool_result: {
      $ref: "#/$defs/toolResult",
    },
    file: {
      $ref: "#/$defs/file",
    },
    interrupt: {
      $ref: "#/$defs/interrupt",
    },
    error: {
      $ref: "#/$defs/error",
    },
  },
  $defs: {
    data: {
      description:
        "A chunk of the streamed reply, rendered as standard Markdown.",
      type: "string",
      minLength: 1,
    },
    currentToolUse: {
      description:
        "A tool the agent is invoking. Welt renders an indicator for it, and takes the fields it recognizes from whatever the framework's own event carries.",
      type: "object",
      properties: {
        name: {
          type: "string",
        },
        toolUseId: {
          type: "string",
        },
      },
    },
    toolResult: {
      description: "A finished tool, which closes that tool's indicator.",
      type: "object",
      properties: {
        toolUseId: {
          type: "string",
        },
        status: {
          enum: ["success", "error"],
        },
      },
    },
    file: {
      description:
        "A file the agent produced, which Welt uploads into the thread.",
      type: "object",
      required: ["name", "bytes"],
      properties: {
        name: {
          description: "The upload filename, extension included.",
          type: "string",
          minLength: 1,
        },
        bytes: {
          description:
            "The file's content, base64-encoded. Welt does refuse a string that fails to decode, which no schema keyword asserts.",
          type: "string",
          contentEncoding: "base64",
        },
      },
    },
    interrupt: {
      description:
        "A question the run stopped on. Welt renders one per pending interrupt and resumes once every one is answered.",
      type: "object",
      required: ["id", "name"],
      properties: {
        id: {
          description: "Identifies the question in the resume payload.",
          type: "string",
          minLength: 1,
        },
        name: {
          description: "Goes to Welt's log only.",
          type: "string",
        },
        reason: {
          description:
            "Any JSON value; its shape alone decides the rendering. The structured shape renders as the widgets it specifies, a non-empty string as that text, anything else as pretty-printed JSON — the latter two with the default Approve / Deny buttons.",
        },
      },
    },
    error: {
      description:
        "A reply failure, normally emitted by the AgentCore Runtime SDK when the agent raises mid-stream rather than by an adapter.",
      type: "string",
    },
    structuredReason: {
      description:
        "The interrupt reason Welt renders as a message with widgets. Matching is all-or-nothing: a reason that fails this falls back to the default rendering rather than being partly repaired.",
      type: "object",
      required: ["message"],
      additionalProperties: false,
      properties: {
        message: {
          description: "The question body, rendered as standard Markdown.",
          type: "string",
          minLength: 1,
        },
        options: {
          description:
            "The choice buttons, at most what one Slack actions block holds.",
          type: "array",
          minItems: 1,
          maxItems: 25,
          items: {
            $ref: "#/$defs/interruptOption",
          },
        },
        input: {
          $ref: "#/$defs/interruptInput",
        },
      },
      anyOf: [
        {
          required: ["options"],
        },
        {
          required: ["input"],
        },
      ],
    },
    interruptOption: {
      type: "object",
      required: ["value"],
      additionalProperties: false,
      properties: {
        value: {
          description:
            "The answer the interrupting tool receives when the button is pressed.",
          type: "string",
          minLength: 1,
          maxLength: 1800,
        },
        label: {
          description: "The button text; defaults to the value.",
          type: "string",
          minLength: 1,
        },
        style: {
          enum: ["primary", "danger"],
        },
      },
    },
    interruptInput: {
      description:
        "The free-text field whose submitted text becomes the answer.",
      type: "object",
      additionalProperties: false,
      properties: {
        label: {
          description: 'The field\'s label; defaults to "Answer".',
          type: "string",
          minLength: 1,
        },
        multiline: {
          description:
            "Whether the field takes more than one line; defaults to false.",
          type: "boolean",
        },
      },
    },
  },
};
