name: Compatibility

on:
  push:
    branches: [main]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions: {}

jobs:
  compatibility:
    permissions:
      contents: read
    uses: iwamot/workflows/.github/workflows/compatibility-node.yml@dc2b7bd58882cf331fdf66a716ca7063eaf975da # v8.5.1
    with:
      node-versions: '["22","24"]'
