name: Compatibility

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions: {}

jobs:
  compatibility:
    permissions:
      contents: read
    uses: iwamot/workflows/.github/workflows/compatibility-node.yml@3a60350ff82e769fc95271d672a481d135d0c059 # v8.8.4
    with:
      node-versions: '["22","24"]'
