name: Compatibility

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions: {}

jobs:
  compatibility:
    permissions:
      contents: read
    uses: iwamot/workflows/.github/workflows/compatibility-node.yml@4fc6b72645ab28986db27f0d96fc94634fda3853 # v8.8.1
    with:
      node-versions: '["22","24"]'
