name: Release

on:
  push:
    tags: ['v*.*.*']

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: production
    permissions:
      contents: write  # to manage the GitHub Release lifecycle
      id-token: write  # for npm Trusted Publishing OIDC
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            api.osv.dev:443
            fulcio.sigstore.dev:443
            github.com:443
            mise-versions.jdx.dev:443
            mise.jdx.dev:443
            nodejs.org:443
            npm.jsr.io:443
            registry.npmjs.org:443
            release-assets.githubusercontent.com:443
            rekor.sigstore.dev:443
            tuf-repo-cdn.sigstore.dev:443

      - uses: iwamot/actions/release-draft@877dcb21b865c1824a70cfebde66313b1d58a860 # v2.8.1
      - uses: iwamot/actions/npm-publish@877dcb21b865c1824a70cfebde66313b1d58a860 # v2.8.1
      - uses: iwamot/actions/release-publish@877dcb21b865c1824a70cfebde66313b1d58a860 # v2.8.1
