name: Release

on:
  push:
    tags: ['v*.*.*']

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: production
    permissions:
      contents: write  # to manage the GitHub Release lifecycle
      id-token: write  # for npm Trusted Publishing OIDC
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - uses: iwamot/actions/release-draft@1d7403ff846ebfd17ac693986b2008313755a05d # v2.0.7
      - uses: iwamot/actions/npm-publish@1d7403ff846ebfd17ac693986b2008313755a05d # v2.0.7
      - uses: iwamot/actions/release-publish@1d7403ff846ebfd17ac693986b2008313755a05d # v2.0.7
